name: Publish NuGet Package

on:
  push:
    branches:
      - release
      - beta
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Display version info
        run: |
          echo "Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          echo "Semantic Version: ${{ steps.gitversion.outputs.semVer }}"
          echo "Assembly Version: ${{ steps.gitversion.outputs.assemblySemVer }}"

      - name: Restore dependencies
        run: dotnet restore Source/ThirteenBytes.DDDPatterns.Primitives/ThirteenBytes.DDDPatterns.Primitives.csproj

      - name: Build
        run: dotnet build Source/ThirteenBytes.DDDPatterns.Primitives/ThirteenBytes.DDDPatterns.Primitives.csproj --configuration Release --no-restore

      - name: Pack NuGet
        run: |
          dotnet pack Source/ThirteenBytes.DDDPatterns.Primitives/ThirteenBytes.DDDPatterns.Primitives.csproj \
            --configuration Release \
            --no-build \
            --output ./packages \
            -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} \
            -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
            -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
            -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}

      - name: Publish to NuGet
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}